export const canvas = document.querySelector('canvas')
export const ctx = canvas.getContext('2d')
export const slider = document.querySelector('.slider1')
export const pause = document.querySelector('.pause1')
export const step = document.querySelector('.step1')
export const reset = document.querySelector('.reset1')