name: Deploy to VPS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.WSL_SSH_PRIVATE_KEY }}

    - name: SSH and pull latest changes
      run: |
        ssh -o StrictHostKeyChecking=no user@your-vps-ip << 'EOF'
          cd ~/game-of-life
          git pull origin main
        EOF